# Generated by Django 5.1.4 on 2024-12-05 06:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('answers', models.FileField(blank=True, help_text='Generated answers file', null=True, upload_to='answers/')),
                ('preview', models.ImageField(blank=True, help_text='PDF preview image', null=True, upload_to='previews/')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processed', 'Processed'), ('failed', 'Processing Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The extracted question from document')),
                ('answer', models.TextField(blank=True, help_text='Generated answer for the question', null=True)),
                ('question_id', models.PositiveIntegerField(help_text='Sequential ID of the question in document', validators=[django.core.validators.MinValueValidator(1)])),
                ('detail_level', models.CharField(choices=[('low', 'Low Detail'), ('medium', 'Medium Detail'), ('high', 'High Detail')], default='medium', help_text='Detail level used for answer generation', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_time', models.FloatField(help_text='Time taken to generate answer in seconds', null=True)),
                ('tokens_used', models.PositiveIntegerField(help_text='Number of tokens used in answer generation', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_responses', to='core.document')),
            ],
            options={
                'verbose_name': 'API Response',
                'verbose_name_plural': 'API Responses',
                'ordering': ['question_id'],
                'indexes': [models.Index(fields=['document', 'question_id'], name='core_apires_documen_8b21cb_idx'), models.Index(fields=['user', 'created_at'], name='core_apires_user_id_200df2_idx')],
                'unique_together': {('document', 'question_id')},
            },
        ),
    ]
